<a href="https://colab.research.google.com/github/parthasarathipanda2006/Projects/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [4]:
x=tf.constant(4,shape=(2,3),dtype=tf.float32)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[4., 4., 4.],
       [4., 4., 4.]], dtype=float32)>

In [5]:
tf.ones((4,5))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [7]:
tf.zeros((3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [6]:
tf.eye(7)

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [9]:
tf.random.normal((3,3),mean=6,stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[5.3795204, 5.796217 , 4.3628235],
       [5.0250072, 5.0507474, 6.160083 ],
       [5.7764473, 6.3817487, 5.5447297]], dtype=float32)>

In [13]:
tf.random.uniform((1,9),minval=6,maxval=9)

<tf.Tensor: shape=(1, 9), dtype=float32, numpy=
array([[8.572199 , 6.4797153, 7.074086 , 7.021247 , 6.537567 , 7.7680397,
        7.943913 , 8.793089 , 8.682426 ]], dtype=float32)>

In [15]:
x=tf.range(start=1,limit=10,delta=3)
tf.cast(x,dtype=tf.float64)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 4., 7.])>

mathematical operation

In [16]:
x=[1,2,3]
y=[2,3,4]
tf.add(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7], dtype=int32)>

In [17]:
tf.subtract(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1, -1, -1], dtype=int32)>

In [19]:
tf.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.5       , 0.66666667, 0.75      ])>

In [21]:
tf.tensordot(x,y,axes=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]], dtype=int32)>

In [25]:
x=tf.random.normal((3,4),mean=0,stddev=1)
y=tf.random.normal((4,4),mean=0,stddev=2)
tf.matmul(x,y)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.88277555,  1.6591246 , -3.9331594 , -0.33073092],
       [-9.0384655 ,  2.6859062 , -3.932961  , -5.191578  ],
       [-1.6940069 , -1.2503586 , -4.1941695 , -0.21949852]],
      dtype=float32)>

In [28]:
x @ y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.88277555,  1.6591246 , -3.9331594 , -0.33073092],
       [-9.0384655 ,  2.6859062 , -3.932961  , -5.191578  ],
       [-1.6940069 , -1.2503586 , -4.1941695 , -0.21949852]],
      dtype=float32)>

indexing


In [29]:
x=[1,2,3,4,56,78]
ind=tf.constant([0,4])
tf.gather(x,ind)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 56], dtype=int32)>

reshape

In [31]:
x=tf.range(9)
y=tf.reshape(x,(3,3))
y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [35]:
tf.transpose(y,perm=[1,0])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>